// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable does not support VITE_* env vars in the browser bundle.
// Use the fixed project URL + anon key.
const SUPABASE_URL = 'https://mrouohttlvirnvmdmwqj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yb3VvaHR0bHZpcm52bWRtd3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MDQ4MDcsImV4cCI6MjA4MTk4MDgwN30.AUNv4x2lREN2AgUhyBN6mYjZGbad3m-B-8ZWrEsNNk0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
